#!/bin/sh

PROJECT_NAME=$1

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

mkdir $1
cd $1
mkdir src

# create build.sh
echo "#!/bin/bash

mkdir -p build/

if [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS settings
  eval cc ./src/main.c -o ./build/${PROJECT_NAME}
else
  gcc ./src/main.c -g -o ./build/${PROJECT_NAME}
fi" >"build.sh"
chmod +x "build.sh"

# create run.sh
echo "./build.sh && ./build/${PROJECT_NAME}" >"run.sh"
chmod +x "run.sh"

touch ./src/main.c
